# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20171229_1851'),
        ('app_two', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_review', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='adds_review',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='review',
            name='book_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklink', to='app_two.Book'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlink', to='app_one.User'),
        ),
    ]
